<?php

namespace modava\contact\controllers;

use modava\contact\components\MyContactController;


class ContactController extends MyContactController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index', []);
    }
}
